#CREATING A STUDENTS TABLE
CREATE TABLE STUDENTS (
STUDENT_NAME VARCHAR2(30),
DEPARTMENT VARCHAR2(30),
AGE NUMBER,
STUDENT_ROLLNO NUMBER);


#INSERTING VALUES TO THE STUDENTS TABLE
INSERT INTO STUDENTS (STUDENT_NAME, DEPARTMENT, AGE, STUDENT_ROLLNO) VALUES ('KRISH', 'CIVIL', 23, 12345);
INSERT INTO STUDENTS (STUDENT_NAME, DEPARTMENT, AGE, STUDENT_ROLLNO) VALUES ('PRIYA', 'CSE', 21, 12346);
INSERT INTO STUDENTS (STUDENT_NAME, DEPARTMENT, AGE, STUDENT_ROLLNO) VALUES ('ARJUN', 'MECH', 22, 12347);
INSERT INTO STUDENTS (STUDENT_NAME, DEPARTMENT, AGE, STUDENT_ROLLNO) VALUES ('DIVYA', 'ECE', 20, 12348);
INSERT INTO STUDENTS (STUDENT_NAME, DEPARTMENT, AGE, STUDENT_ROLLNO) VALUES ('RAHUL', 'EEE', 24, 12349);
INSERT INTO STUDENTS (STUDENT_NAME, DEPARTMENT, AGE, STUDENT_ROLLNO) VALUES ('MEENA', 'IT', 22, 12350);
INSERT INTO STUDENTS (STUDENT_NAME, DEPARTMENT, AGE, STUDENT_ROLLNO) VALUES ('SURESH', 'CIVIL', 23, 12351);
INSERT INTO STUDENTS (STUDENT_NAME, DEPARTMENT, AGE, STUDENT_ROLLNO) VALUES ('ANJALI', 'CSE', 21, 12352);
INSERT INTO STUDENTS (STUDENT_NAME, DEPARTMENT, AGE, STUDENT_ROLLNO) VALUES ('VIKRAM', 'MECH', 24, 12353);
INSERT INTO STUDENTS (STUDENT_NAME, DEPARTMENT, AGE, STUDENT_ROLLNO) VALUES ('NEHA', 'ECE', 22, 12354);

#SHOWING THE VALUES OF THE STUDENTS TABLE
SELECT * FROM STUDENTS;

#RENAMING THE STUDENT_NAME COLUMN INTO FIRST_NAME
ALTER TABLE STUDENTS RENAME COLUMN STUDENT_NAME TO FIRST_NAME;

#ADDING A NEW COLUMN LAST_NAME TO THE EXISTING TABLE
ALTER TABLE STUDENTS ADD LAST_NAME VARCHAR2(30);

#UPDATING VALUES TO THE LAST NAME COLUMN
UPDATE STUDENTS SET LAST_NAME = 'PREET' WHERE STUDENT_ROLLNO = 12345;
UPDATE STUDENTS SET LAST_NAME = 'KUMAR' WHERE STUDENT_ROLLNO = 12346;
UPDATE STUDENTS SET LAST_NAME = 'SHARMA' WHERE STUDENT_ROLLNO = 12347;
UPDATE STUDENTS SET LAST_NAME = 'NAIR' WHERE STUDENT_ROLLNO = 12348;
UPDATE STUDENTS SET LAST_NAME = 'REDDY' WHERE STUDENT_ROLLNO = 12349;
UPDATE STUDENTS SET LAST_NAME = 'SINGH' WHERE STUDENT_ROLLNO = 12350;
UPDATE STUDENTS SET LAST_NAME = 'PATEL' WHERE STUDENT_ROLLNO = 12351;
UPDATE STUDENTS SET LAST_NAME = 'RAO' WHERE STUDENT_ROLLNO = 12352;
UPDATE STUDENTS SET LAST_NAME = 'VERMA' WHERE STUDENT_ROLLNO = 12353;
UPDATE STUDENTS SET LAST_NAME = 'CHOWDHURY' WHERE STUDENT_ROLLNO = 12354;

#ADDING A NEW COLUMN DATE OF BIRTH
ALTER TABLE STUDENTS ADD DOB DATE;

#UPDATING THE DATE OF BIRTH FOR ALL THE STUDENTS
UPDATE STUDENTS SET DOB = TO_DATE('15-02-2002', 'DD-MM-YYYY') WHERE STUDENT_ROLLNO = 12345;
UPDATE STUDENTS SET DOB = TO_DATE('10-08-2003', 'DD-MM-YYYY') WHERE STUDENT_ROLLNO = 12346;
UPDATE STUDENTS SET DOB = TO_DATE('25-05-2002', 'DD-MM-YYYY') WHERE STUDENT_ROLLNO = 12347;
UPDATE STUDENTS SET DOB = TO_DATE('30-11-2004', 'DD-MM-YYYY') WHERE STUDENT_ROLLNO = 12348;
UPDATE STUDENTS SET DOB = TO_DATE('12-07-2001', 'DD-MM-YYYY') WHERE STUDENT_ROLLNO = 12349;
UPDATE STUDENTS SET DOB = TO_DATE('09-09-2003', 'DD-MM-YYYY') WHERE STUDENT_ROLLNO = 12350;
UPDATE STUDENTS SET DOB = TO_DATE('22-01-2002', 'DD-MM-YYYY') WHERE STUDENT_ROLLNO = 12351;
UPDATE STUDENTS SET DOB = TO_DATE('14-06-2004', 'DD-MM-YYYY') WHERE STUDENT_ROLLNO = 12352;
UPDATE STUDENTS SET DOB = TO_DATE('19-10-2001', 'DD-MM-YYYY') WHERE STUDENT_ROLLNO = 12353;
UPDATE STUDENTS SET DOB = TO_DATE('03-03-2003', 'DD-MM-YYYY') WHERE STUDENT_ROLLNO = 12354;



#FETCHING THE DATA FROM DATABASE
SELECT * FROM STUDENTS;

#FETCHING A PARTICULAR STUDENT DATA WITH THEIR ROLL NUMBER
SELECT * FROM STUDENTS WHERE STUDENT_ROLLNO=12352;

#FETCHING A PARTICULAR COLUMN FROM THE TABLE 
SELECT FIRST_NAME,STUDENT_ROLLNO FROM STUDENTS WHERE STUDENT_ROLLNO=12354;

#CONCATINATING THE FIRST_NAME AND LAST_NAME OF THE STUDENTS TABLE
SELECT FIRST_NAME|| ' ' ||LAST_NAME AS FULL_NAME FROM STUDENTS;

#CONCATINATING THE FIRST_NAME AND ROLLNO
SELECT FIRST_NAME||'"S ROLLNO IS ' ||STUDENT_ROLLNO  AS ROLLNO FROM STUDENTS;




#RELATIONAL OPERATORS

#FETCHING DATA OF STUDENTS WITH FILTER
SELECT * FROM STUDENTS WHERE AGE>24;

#SPECIAL OPERATORS

#IN 
SELECT * FROM STUDENTS
WHERE AGE IN (23,24,25);

#NOT IN
SELECT * FROM STUDENTS 
WHERE AGE NOT IN (24,23);

#BETWEEN
SELECT * FROM STUDENTS 
WHERE AGE BETWEEN 22 AND 24;

#NOT BETWEEN
SELECT * FROM STUDENTS 
WHERE AGE NOT BETWEEN 22 AND 24;

#LIKE 
#FETCH STUDENTS WITH FIRST_NAME STARTS WITH P AND ENDS WITH A 
#  "%" USED FOR MULTI LETTER SEARCH
SELECT * FROM STUDENTS 
WHERE FIRST_NAME LIKE 'P%A';

#FETCH STUDENTS WITH LAST_NAME ENDS WITH _AIR 
# "_" USED FOR SINGLE LETTER SEARCH
SELECT * FROM STUDENTS 
WHERE LAST_NAME LIKE '_AIR';

#GETTING DETAILS OF STUDENTS WHOS ROLLNO IS NOT NULL
SELECT * FROM STUDENTS
WHERE STUDENT_ROLLNO IS NOT NULL;

CREATE TABLE STUDENT_MARKS (
  FIRST_NAME VARCHAR2(30),
  LAST_NAME  VARCHAR2(30),
  WEIGHT     FLOAT,
  MARKS      NUMBER
);

INSERT INTO STUDENT_MARKS VALUES ('KRISH',  'PREET',    68.5,   9);
INSERT INTO STUDENT_MARKS VALUES ('PRIYA',  'KUMAR',    54.2,  -3);
INSERT INTO STUDENT_MARKS VALUES ('ARJUN',  'SHARMA',   72.8,   5);
INSERT INTO STUDENT_MARKS VALUES ('DIVYA',  'NAIR',     49.6,  -7);
INSERT INTO STUDENT_MARKS VALUES ('RAHUL',  'REDDY',    80.3,   8);
INSERT INTO STUDENT_MARKS VALUES ('MEENA',  'SINGH',    57.9,  -2);
INSERT INTO STUDENT_MARKS VALUES ('SURESH', 'PATEL',    75.4,   6);
INSERT INTO STUDENT_MARKS VALUES ('ANJALI', 'RAO',      61.1,  -4);
INSERT INTO STUDENT_MARKS VALUES ('VIKRAM', 'VERMA',    85.7,   9);
INSERT INTO STUDENT_MARKS VALUES ('NEHA',   'CHOWDHURY',52.5,  -1);




#SINGLE ROW FUNCTION

#CHANGING THE FIRST NAME AND LAST NAME INTO LOWERCASE AND CONCATINATE IT
SELECT LOWER(FIRST_NAME || ' ' ||LAST_NAME) AS FULL_NAME FROM STUDENT_MARKS;

#CHANGE THE FIRST_NAME AND LAST_NAME FIRST LETTER CAPS AND CONCATINATE IT
SELECT INITCAP(FIRST_NAME || ' ' ||LAST_NAME) AS FULL_NAME FROM STUDENT_MARKS;

#CALCUATING THE LENGTH OF THE LASTNAME OF EACH STUDENTS
SELECT FIRST_NAME,LENGTH(LAST_NAME) AS LENGTH_OF_LASTNAME FROM STUDENT_MARKS;

#CONCATINATING MR/MRS TO THE FIRST_NAME OF EACH STUDENTS
SELECT CONCAT('MR/MRS ',FIRST_NAME) AS NAME FROM STUDENT_MARKS;

#REVERSE ALL THE FIRST_NAME OF THE STUDENTS
SELECT REVERSE(FIRST_NAME) AS REVERSED_NAME FROM STUDENT_MARKS;

#GETTING FIRST 3 LETTER FROM THE FIRST_NAME
SELECT SUBSTR(FIRST_NAME,1,3) AS FIRST_3_LETTERS FROM STUDENT_MARKS;

#GET THE POSOTION OF A LETTER FROM THE FIRSTNAME
SELECT FIRST_NAME ,INSTR(FIRST_NAME,'E') AS POSITION_OF_E FROM STUDENT_MARKS;

#ADDING VALUES TO THE LEFT OF THE STRING OR INTEGER
SELECT LPAD('123',8,0) FROM DUAL;

#ADDING VALUES TO THE RIGHT OF THE STRING OR INTEGER
SELECT RPAD('123',8,0) FROM DUAL;

#TRIM THE EXCESS SPACE FROM THE STRING
SELECT TRIM('    RAM  ') FROM DUAL;

#REPLACE  
SELECT REPLACE('WHAT DO YOU WANT','AT','XY') FROM DUAL;

#TRANSLATE
SELECT TRANSLATE('WHAT DO YOU WANT','WA','XY') FROM DUAL;


#NUMBER FUNCTION
#ROUND() FUNCTION
SELECT ROUND(WEIGHT) FROM STUDENT_MARKS; 

#MOD() FUNCTION
SELECT MOD(100,3) FROM DUAL;

#POWER() FUNCTION
SELECT POWER(10,3) FROM DUAL;

#ABS() FUNCTION
SELECT ABS(MARKS) FROM STUDENT_MARKS;

#SIGN() FUNCTION
SELECT SIGN(MARKS) FROM STUDENT_MARKS;

#CEIL() FUNCTION
SELECT CEIL(WEIGHT) AS MAX_WEIGHT FROM STUDENT_MARKS;

#FLOOR() FUNCITON
SELECT FLOOR(WEIGHT) AS MIN_WEIGHT FROM STUDENT_MARKS;


#DATE FUNCITON
#MONTHS_BETWEEN()
SELECT ROUND(MONTHS_BETWEEN(SYSDATE,DOB)) FROM STUDENTS; #BUG

#ADD MONTHS TO EXISTING 
SELECT DOB,ADD_MONTHS(DOB,1) AS INCREASED_DOB FROM STUDENTS;

#NEXT_DAY
SELECT DOB AS CURRENT_DAY ,NEXT_DAY(DOB,'SATURDAY') AS NEXT_SATURDAY FROM STUDENTS;

#ORDERBY FUNCTION
SELECT * FROM STUDENTS
ORDER BY AGE ASC;

SELECT * FROM STUDENT_MARKS
WHERE MARKS IN (9,8,-7,-1)
ORDER BY WEIGHT DESC;
